In [1]:
# Initial imports
import pandas as pd
from path import Path
from sqlalchemy import create_engine
from config import db_password

In [2]:
# Load the season_stats.csv dataset.
csv_path = Path("season_stats.csv")
stats_df = pd.read_csv(csv_path)
stats_df.head()

,Position,Season,Tm,Team_Name,Lg,G,W,L,W/L%,MOV,...,eFG%,TS%,TOV%,ORB%,FT/FGA,opp_eFG%,opp_TS%,opp_TOV%,opp_ORB%,opp_FT/FGA
0,0,2020-21,WAS,Washington Wizards,NBA,72,34,38,0.472,-1.83,...,0.531,0.569,12.3,21.3,0.221,0.539,0.576,12.5,22.4,0.217
1,0,2020-21,UTA,Utah Jazz,NBA,72,52,20,0.722,9.25,...,0.563,0.597,12.7,24.5,0.195,0.507,0.537,10.3,20.7,0.159
2,0,2020-21,TOR,Toronto Raptors,NBA,72,27,45,0.375,-0.47,...,0.529,0.567,11.9,20.8,0.196,0.543,0.584,14.4,23.7,0.234
3,0,2020-21,SAS,San Antonio Spurs,NBA,72,33,39,0.458,-1.74,...,0.517,0.554,10.2,20.0,0.192,0.541,0.570,11.8,22.7,0.174
4,0,2020-21,SAC,Sacramento Kings,NBA,72,31,41,0.431,-3.68,...,0.549,0.578,12.0,21.3,0.185,0.557,0.591,12.1,25.0,0.199

In [3]:
# remove usless columns
stats_df = stats_df.drop(['Team_Name','Lg'], axis=1)
stats_df.head()

,Position,Season,Tm,G,W,L,W/L%,MOV,SOS,SRS,...,eFG%,TS%,TOV%,ORB%,FT/FGA,opp_eFG%,opp_TS%,opp_TOV%,opp_ORB%,opp_FT/FGA
0,0,2020-21,WAS,72,34,38,0.472,-1.83,-0.01,-1.85,...,0.531,0.569,12.3,21.3,0.221,0.539,0.576,12.5,22.4,0.217
1,0,2020-21,UTA,72,52,20,0.722,9.25,-0.29,8.97,...,0.563,0.597,12.7,24.5,0.195,0.507,0.537,10.3,20.7,0.159
2,0,2020-21,TOR,72,27,45,0.375,-0.47,-0.07,-0.54,...,0.529,0.567,11.9,20.8,0.196,0.543,0.584,14.4,23.7,0.234
3,0,2020-21,SAS,72,33,39,0.458,-1.74,0.15,-1.58,...,0.517,0.554,10.2,20.0,0.192,0.541,0.570,11.8,22.7,0.174
4,0,2020-21,SAC,72,31,41,0.431,-3.68,0.23,-3.45,...,0.549,0.578,12.0,21.3,0.185,0.557,0.591,12.1,25.0,0.199

In [4]:
stats_df = stats_df.rename(columns={'W/L%': 'Win_pct', 'eFG%': 'eFG_pct','TS%': 'TS_pct', 'TOV%': 'TOV_pct', 'ORB%': 'ORB_pct' ,'FT/FGA': 'FT_FGA',
                                   'opp_eFG%': 'Opp_eFG_pct','opp_TS%': 'Opp_TS_pct', 'opp_TOV%': 'Opp_TOV_pct', 'opp_ORB%': 'Opp_ORB_pct', 'opp_FT/FGA': 'Opp_FT_FGA' })
stats_df.head()

,Position,Season,Tm,G,W,L,Win_pct,MOV,SOS,SRS,...,eFG_pct,TS_pct,TOV_pct,ORB_pct,FT_FGA,Opp_eFG_pct,Opp_TS_pct,Opp_TOV_pct,Opp_ORB_pct,Opp_FT_FGA
0,0,2020-21,WAS,72,34,38,0.472,-1.83,-0.01,-1.85,...,0.531,0.569,12.3,21.3,0.221,0.539,0.576,12.5,22.4,0.217
1,0,2020-21,UTA,72,52,20,0.722,9.25,-0.29,8.97,...,0.563,0.597,12.7,24.5,0.195,0.507,0.537,10.3,20.7,0.159
2,0,2020-21,TOR,72,27,45,0.375,-0.47,-0.07,-0.54,...,0.529,0.567,11.9,20.8,0.196,0.543,0.584,14.4,23.7,0.234
3,0,2020-21,SAS,72,33,39,0.458,-1.74,0.15,-1.58,...,0.517,0.554,10.2,20.0,0.192,0.541,0.570,11.8,22.7,0.174
4,0,2020-21,SAC,72,31,41,0.431,-3.68,0.23,-3.45,...,0.549,0.578,12.0,21.3,0.185,0.557,0.591,12.1,25.0,0.199

In [2]:
# Load the cy_stats.csv dataset.
csv_path = Path("cy_stats.csv")
cy_stats_df = pd.read_csv(csv_path)
cy_stats_df

,Position,Season,Tm,Lg,G,W,L,W/L%,MOV,SOS,...,eFG%,TS%,TOV%,ORB%,FT/FGA,opp_eFG%,opp_TS%,opp_TOV%,opp_ORB%,opp_FT/FGA
0,0,2021-22,GSW,NBA,10,9,1,0.900,13.70,-3.49,...,0.563,0.591,13.9,20.1,0.166,0.492,0.522,14.6,17.1,0.166
1,0,2021-22,UTA,NBA,11,8,3,0.727,9.36,-0.63,...,0.536,0.577,13.7,25.7,0.220,0.493,0.524,11.1,19.8,0.160
2,0,2021-22,PHI,NBA,12,8,4,0.667,5.75,-2.03,...,0.554,0.587,12.0,20.6,0.174,0.501,0.535,12.0,27.0,0.170
3,0,2021-22,MIA,NBA,10,7,3,0.700,8.60,-0.03,...,0.529,0.570,13.2,25.3,0.208,0.494,0.530,12.1,18.9,0.192
4,0,2021-22,WAS,NBA,10,7,3,0.700,4.40,0.29,...,0.523,0.560,12.8,19.6,0.199,0.480,0.518,10.7,21.6,0.181
5,0,2021-22,NYK,NBA,11,7,4,0.636,2.36,-0.55,...,0.532,0.565,12.0,23.4,0.190,0.515,0.551,11.8,23.0,0.175
6,0,2021-22,DAL,NBA,10,7,3,0.700,-2.30,-0.95,...,0.503,0.531,12.2,21.7,0.165,0.519,0.547,12.5,20.6,0.156
7,0,2021-22,CLE,NBA,11,7,4,0.636,1.09,0.52,...,0.525,0.558,14.8,25.4,0.185,0.511,0.534,12.8,26.7,0.125
8,0,2021-22,BRK,NBA,11,7,4,0.636,0.45,0.10,...,0.538,0.570,14.4,16.2,0.180,0.485,0.518,10.5,21.4,0.160
9,0,2021-22,CHI,NBA,10,7,3,0.700,7.00,-1.18,...,0.516,0.562,11.4,21.2,0.215,0.507,0.539,14.7,22.0,0.164
10,0,2021-22,DEN,NBA,10,6,4,0.600,3.40,-0.37,...,0.525,0.545,14.5,20.3,0.124,0.506,0.537,14.7,19.2,0.166
11,0,2021-22,TOR,NBA,11,6,5,0.545,2.91,1.07,...,0.492,0.522,11.3,29.2,0.151,0.526,0.563,16.2,22.5,0.194
12,0,2021-22,LAC,NBA,10,6,4,0.600,4.80,-0.21,...,0.525,0.554,12.4,18.5,0.163,0.496,0.527,15.2,23.8,0.153
13,0,2021-22,LAL,NBA,11,6,5,0.545,-0.82,-1.77,...,0.526,0.553,14.1,22.0,0.163,0.519,0.549,14.5,25.3,0.188
14,0,2021-22,MEM,NBA,10,6,4,0.600,-3.90,2.95,...,0.513,0.542,12.4,26.4,0.147,0.556,0.581,13.2,22.4,0.155
15,0,2021-22,PHO,NBA,9,6,3,0.667,0.89,-1.48,...,0.535,0.566,12.7,19.3,0.177,0.526,0.557,14.4,20.9,0.166
16,0,2021-22,SAC,NBA,11,5,6,0.455,1.09,0.32,...,0.524,0.562,12.6,20.4,0.198,0.508,0.539,11.9,23.5,0.171
17,0,2021-22,MIL,NBA,11,5,6,0.455,-0.91,0.65,...,0.514,0.543,12.3,21.5,0.167,0.511,0.542,12.0,22.4,0.169
18,0,2021-22,POR,NBA,11,5,6,0.455,1.91,1.46,...,0.535,0.560,12.3,23.3,0.150,0.542,0.564,12.6,18.3,0.149
19,0,2021-22,CHO,NBA,12,5,7,0.417,-4.08,1.95,...,0.518,0.546,11.5,23.5,0.166,0.560,0.595,14.4,24.2,0.198
20,0,2021-22,BOS,NBA,10,4,6,0.400,-1.40,0.93,...,0.503,0.538,12.1,20.6,0.181,0.509,0.549,13.7,23.4,0.206
21,0,2021-22,ATL,NBA,12,4,8,0.333,-4.00,1.38,...,0.511,0.545,11.8,24.3,0.167,0.541,0.575,11.8,20.2,0.172
22,0,2021-22,IND,NBA,11,4,7,0.364,-0.36,2.16,...,0.537,0.564,14.6,22.9,0.151,0.515,0.551,12.3,21.7,0.190
23,0,2021-22,ORL,NBA,11,3,8,0.273,-7.27,-0.04,...,0.504,0.536,15.0,21.8,0.167,0.509,0.542,11.3,24.6,0.186
24,0,2021-22,OKC,NBA,9,3,6,0.333,-9.33,2.50,...,0.472,0.506,13.7,20.5,0.170,0.522,0.546,12.3,23.4,0.126
25,0,2021-22,MIN,NBA,9,3,6,0.333,-4.11,-2.96,...,0.490,0.520,14.7,25.7,0.148,0.515,0.555,16.3,29.5,0.207
26,0,2021-22,SAS,NBA,10,3,7,0.300,0.40,-2.62,...,0.512,0.532,11.9,20.0,0.119,0.521,0.545,15.1,22.5,0.140
27,0,2021-22,NOP,NBA,11,1,10,0.091,-11.73,0.34,...,0.482,0.515,14.4,25.0,0.152,0.554,0.588,12.2,20.8,0.184
28,0,2021-22,HOU,NBA,10,1,9,0.100,-7.40,-0.14,...,0.513,0.545,17.2,21.8,0.198,0.527,0.560,13.5,22.5,0.185
29,0,2021-22,DET,NBA,9,1,8,0.111,-12.33,1.11,...,0.450,0.488,13.6,22.3,0.181,0.560,0.592,15.9,20.1,0.181

In [3]:
cy_stats_df = cy_stats_df.rename(columns={'W/L%': 'Win_pct', 'eFG%': 'eFG_pct','TS%': 'TS_pct', 'TOV%': 'TOV_pct', 'ORB%': 'ORB_pct' ,'FT/FGA': 'FT_FGA',
                                   'opp_eFG%': 'Opp_eFG_pct','opp_TS%': 'Opp_TS_pct', 'opp_TOV%': 'Opp_TOV_pct', 'opp_ORB%': 'Opp_ORB_pct', 'opp_FT/FGA': 'Opp_FT_FGA' })
cy_stats_df.head()

,Position,Season,Tm,Lg,G,W,L,Win_pct,MOV,SOS,...,eFG_pct,TS_pct,TOV_pct,ORB_pct,FT_FGA,Opp_eFG_pct,Opp_TS_pct,Opp_TOV_pct,Opp_ORB_pct,Opp_FT_FGA
0,0,2021-22,GSW,NBA,10,9,1,0.900,13.70,-3.49,...,0.563,0.591,13.9,20.1,0.166,0.492,0.522,14.6,17.1,0.166
1,0,2021-22,UTA,NBA,11,8,3,0.727,9.36,-0.63,...,0.536,0.577,13.7,25.7,0.220,0.493,0.524,11.1,19.8,0.160
2,0,2021-22,PHI,NBA,12,8,4,0.667,5.75,-2.03,...,0.554,0.587,12.0,20.6,0.174,0.501,0.535,12.0,27.0,0.170
3,0,2021-22,MIA,NBA,10,7,3,0.700,8.60,-0.03,...,0.529,0.570,13.2,25.3,0.208,0.494,0.530,12.1,18.9,0.192
4,0,2021-22,WAS,NBA,10,7,3,0.700,4.40,0.29,...,0.523,0.560,12.8,19.6,0.199,0.480,0.518,10.7,21.6,0.181

In [4]:
cy_stats_df = cy_stats_df.drop(['Lg'], axis=1)
cy_stats_df.head()

,Position,Season,Tm,G,W,L,Win_pct,MOV,SOS,SRS,...,eFG_pct,TS_pct,TOV_pct,ORB_pct,FT_FGA,Opp_eFG_pct,Opp_TS_pct,Opp_TOV_pct,Opp_ORB_pct,Opp_FT_FGA
0,0,2021-22,GSW,10,9,1,0.900,13.70,-3.49,10.21,...,0.563,0.591,13.9,20.1,0.166,0.492,0.522,14.6,17.1,0.166
1,0,2021-22,UTA,11,8,3,0.727,9.36,-0.63,8.73,...,0.536,0.577,13.7,25.7,0.220,0.493,0.524,11.1,19.8,0.160
2,0,2021-22,PHI,12,8,4,0.667,5.75,-2.03,3.72,...,0.554,0.587,12.0,20.6,0.174,0.501,0.535,12.0,27.0,0.170
3,0,2021-22,MIA,10,7,3,0.700,8.60,-0.03,8.57,...,0.529,0.570,13.2,25.3,0.208,0.494,0.530,12.1,18.9,0.192
4,0,2021-22,WAS,10,7,3,0.700,4.40,0.29,4.69,...,0.523,0.560,12.8,19.6,0.199,0.480,0.518,10.7,21.6,0.181

In [5]:
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/nba_champs"

In [6]:
engine = create_engine(db_string)

In [11]:
stats_df.to_sql(name='stats', con=engine)

In [7]:
cy_stats_df.to_sql(name='cy_stats', con=engine)

OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/14/e3q8)