In [1]:
# Initial imports
import pandas as pd
from path import Path

In [19]:
# Load the stats.csv dataset.
csv_path = Path("stats.csv")
stats_df = pd.read_csv(csv_path)
stats_df.head()

,Rk,Season,Tm,Lg,G,W,L,W/L%,MOV,SOS,...,eFG%,TS%,TOV%,ORB%,FT/FGA,opp_eFG%,opp_TS%,opp_TOV%,opp_ORB%,opp_FT/FGA
0,1,2020-21,WAS*,NBA,72,34,38,0.472,-1.83,-0.01,...,0.531,0.569,12.3,21.3,0.221,0.539,0.576,12.5,22.4,0.217
1,2,2020-21,UTA*,NBA,72,52,20,0.722,9.25,-0.29,...,0.563,0.597,12.7,24.5,0.195,0.507,0.537,10.3,20.7,0.159
2,3,2020-21,TOR,NBA,72,27,45,0.375,-0.47,-0.07,...,0.529,0.567,11.9,20.8,0.196,0.543,0.584,14.4,23.7,0.234
3,4,2020-21,SAS,NBA,72,33,39,0.458,-1.74,0.15,...,0.517,0.554,10.2,20.0,0.192,0.541,0.570,11.8,22.7,0.174
4,5,2020-21,SAC,NBA,72,31,41,0.431,-3.68,0.23,...,0.549,0.578,12.0,21.3,0.185,0.557,0.591,12.1,25.0,0.199

In [20]:
#Process stats df 
stats_df['abbr'] = stats_df['Tm'].str.slice(stop=3)
stats_df['Year'] = stats_df['Season'].str.slice(start=5)
stats_df.head()

,Rk,Season,Tm,Lg,G,W,L,W/L%,MOV,SOS,...,TOV%,ORB%,FT/FGA,opp_eFG%,opp_TS%,opp_TOV%,opp_ORB%,opp_FT/FGA,abbr,Year
0,1,2020-21,WAS*,NBA,72,34,38,0.472,-1.83,-0.01,...,12.3,21.3,0.221,0.539,0.576,12.5,22.4,0.217,WAS,21
1,2,2020-21,UTA*,NBA,72,52,20,0.722,9.25,-0.29,...,12.7,24.5,0.195,0.507,0.537,10.3,20.7,0.159,UTA,21
2,3,2020-21,TOR,NBA,72,27,45,0.375,-0.47,-0.07,...,11.9,20.8,0.196,0.543,0.584,14.4,23.7,0.234,TOR,21
3,4,2020-21,SAS,NBA,72,33,39,0.458,-1.74,0.15,...,10.2,20.0,0.192,0.541,0.570,11.8,22.7,0.174,SAS,21
4,5,2020-21,SAC,NBA,72,31,41,0.431,-3.68,0.23,...,12.0,21.3,0.185,0.557,0.591,12.1,25.0,0.199,SAC,21

In [21]:
# remove usless columns
stats_df = stats_df.drop(['Rk', 'Season', 'Tm', 'Lg'], axis=1)
stats_df.head()

,G,W,L,W/L%,MOV,SOS,SRS,Pace,ORtg,DRtg,...,TOV%,ORB%,FT/FGA,opp_eFG%,opp_TS%,opp_TOV%,opp_ORB%,opp_FT/FGA,abbr,Year
0,72,34,38,0.472,-1.83,-0.01,-1.85,104.1,111.2,113.0,...,12.3,21.3,0.221,0.539,0.576,12.5,22.4,0.217,WAS,21
1,72,52,20,0.722,9.25,-0.29,8.97,98.5,117.6,108.3,...,12.7,24.5,0.195,0.507,0.537,10.3,20.7,0.159,UTA,21
2,72,27,45,0.375,-0.47,-0.07,-0.54,99.2,112.0,112.5,...,11.9,20.8,0.196,0.543,0.584,14.4,23.7,0.234,TOR,21
3,72,33,39,0.458,-1.74,0.15,-1.58,98.9,111.0,112.8,...,10.2,20.0,0.192,0.541,0.570,11.8,22.7,0.174,SAS,21
4,72,31,41,0.431,-3.68,0.23,-3.45,100.0,113.6,117.2,...,12.0,21.3,0.185,0.557,0.591,12.1,25.0,0.199,SAC,21

In [39]:
# Load the champions.csv dataset.
csv_path = Path("champions.csv")
champions_df = pd.read_csv(csv_path)
champions_df

,Year,Lg,Champion,Runner-Up,Finals MVP,Unnamed: 5,Points,Rebounds,Assists,Win Shares
0,2021,NBA,Milwaukee Bucks,Phoenix Suns,G. Antetokounmpo,NaN,G. Antetokounmpo (634),G. Antetokounmpo (269),J. Holiday (199),G. Antetokounmpo (3.7)
1,2020,NBA,Los Angeles Lakers,Miami Heat,L. James,NaN,A. Davis (582),L. James (226),L. James (184),A. Davis (4.5)
2,2019,NBA,Toronto Raptors,Golden State Warriors,K. Leonard,NaN,K. Leonard (732),D. Green (223),D. Green (187),K. Leonard (4.9)
3,2018,NBA,Golden State Warriors,Cleveland Cavaliers,K. Durant,NaN,L. James (748),D. Green (222),L. James (198),L. James (5.2)
4,2017,NBA,Golden State Warriors,Cleveland Cavaliers,K. Durant,NaN,L. James (591),K. Love (191),L. James (141),L. James (4.3)
...,...,...,...,...,...,...,...,...,...,...
79,1951,NBA,Rochester Royals,New York Knicks,NaN,NaN,A. Risen (273),A. Risen (196),D. McGuire (78),B. Wanzer (2.7)
80,1950,NBA,Minneapolis Lakers,Syracuse Nationals,NaN,NaN,G. Mikan (376),NaN,J. Pollard (56),G. Mikan (3.7)
81,1949,BAA,Minneapolis Lakers,Washington Capitols,NaN,NaN,G. Mikan (303),NaN,J. Pollard (39),G. Mikan (4.2)
82,1948,BAA,Baltimore Bullets,Philadelphia Warriors,NaN,NaN,J. Fulks (282),NaN,H. Dallmar (37),C. Simmons (2.5)
83,1947,BAA,Philadelphia Warriors,Chicago Stags,NaN,NaN,J. Fulks (222),NaN,H. Dallmar (16),J. Fulks (2.3)

In [40]:
#Sort Champions df to only show Champions after 1990
champions_df = champions_df[(champions_df['Year'] > 1990)]
champions_df

,Year,Lg,Champion,Runner-Up,Finals MVP,Unnamed: 5,Points,Rebounds,Assists,Win Shares
0,2021,NBA,Milwaukee Bucks,Phoenix Suns,G. Antetokounmpo,NaN,G. Antetokounmpo (634),G. Antetokounmpo (269),J. Holiday (199),G. Antetokounmpo (3.7)
1,2020,NBA,Los Angeles Lakers,Miami Heat,L. James,NaN,A. Davis (582),L. James (226),L. James (184),A. Davis (4.5)
2,2019,NBA,Toronto Raptors,Golden State Warriors,K. Leonard,NaN,K. Leonard (732),D. Green (223),D. Green (187),K. Leonard (4.9)
3,2018,NBA,Golden State Warriors,Cleveland Cavaliers,K. Durant,NaN,L. James (748),D. Green (222),L. James (198),L. James (5.2)
4,2017,NBA,Golden State Warriors,Cleveland Cavaliers,K. Durant,NaN,L. James (591),K. Love (191),L. James (141),L. James (4.3)
5,2016,NBA,Cleveland Cavaliers,Golden State Warriors,L. James,NaN,K. Thompson (582),D. Green (228),R. Westbrook (198),L. James (4.7)
6,2015,NBA,Golden State Warriors,Cleveland Cavaliers,A. Iguodala,NaN,L. James (601),D. Howard (238),L. James (169),S. Curry (3.9)
7,2014,NBA,San Antonio Spurs,Miami Heat,K. Leonard,NaN,K. Durant (563),T. Duncan (211),R. Westbrook (153),L. James (4.3)
8,2013,NBA,Miami Heat,San Antonio Spurs,L. James,NaN,L. James (596),T. Duncan (214),L. James (152),L. James (5.2)
9,2012,NBA,Miami Heat,Oklahoma City Thunder,L. James,NaN,L. James (697),L. James (224),R. Rondo (227),L. James (5.8)
10,2011,NBA,Dallas Mavericks,Miami Heat,D. Nowitzki,NaN,D. Nowitzki (582),T. Chandler (193),J. Kidd (153),L. James (3.8)
11,2010,NBA,Los Angeles Lakers,Boston Celtics,K. Bryant,NaN,K. Bryant (671),P. Gasol (255),R. Rondo (223),P. Gasol (4.3)
12,2009,NBA,Los Angeles Lakers,Orlando Magic,K. Bryant,NaN,K. Bryant (695),D. Howard (353),R. Rondo (137),L. James (4.8)
13,2008,NBA,Boston Celtics,Los Angeles Lakers,P. Pierce,NaN,K. Bryant (633),K. Garnett (274),R. Rondo (172),K. Garnett (4.1)
14,2007,NBA,San Antonio Spurs,Cleveland Cavaliers,T. Parker,NaN,L. James (501),T. Duncan (229),L. James (159),L. James (3.7)
15,2006,NBA,Miami Heat,Dallas Mavericks,D. Wade,NaN,D. Wade (654),D. Nowitzki (268),S. Nash (204),D. Nowitzki (5.4)
16,2005,NBA,San Antonio Spurs,Detroit Pistons,T. Duncan,NaN,T. Duncan (542),T. Duncan (286),S. Nash (170),C. Billups (4.6)
17,2004,NBA,Detroit Pistons,Los Angeles Lakers,C. Billups,NaN,K. Bryant (539),B. Wallace (328),C. Billups (136),S. O'Neal (3.9)
18,2003,NBA,San Antonio Spurs,New Jersey Nets,T. Duncan,NaN,T. Duncan (593),T. Duncan (369),J. Kidd (163),T. Duncan (5.9)
19,2002,NBA,Los Angeles Lakers,New Jersey Nets,S. O'Neal,NaN,S. O'Neal (541),S. O'Neal (239),J. Kidd (182),S. O'Neal (3.8)
20,2001,NBA,Los Angeles Lakers,Philadelphia 76ers,S. O'Neal,NaN,A. Iverson (723),D. Mutombo (316),A. Iverson (134),K. Bryant (3.8)
21,2000,NBA,Los Angeles Lakers,Indiana Pacers,S. O'Neal,NaN,S. O'Neal (707),S. O'Neal (355),M. Jackson (178),S. O'Neal (4.7)
22,1999,NBA,San Antonio Spurs,New York Knicks,T. Duncan,NaN,L. Sprewell (407),T. Duncan (195),A. Johnson (126),T. Duncan (3.7)
23,1998,NBA,Chicago Bulls,Utah Jazz,M. Jordan,NaN,M. Jordan (680),D. Rodman (248),J. Stockton (155),M. Jordan (4.8)
24,1997,NBA,Chicago Bulls,Utah Jazz,M. Jordan,NaN,M. Jordan (590),K. Malone (228),J. Stockton (191),M. Jordan (3.9)
25,1996,NBA,Chicago Bulls,Seattle SuperSonics,M. Jordan,NaN,M. Jordan (552),D. Rodman (247),J. Stockton (195),M. Jordan (4.7)
26,1995,NBA,Houston Rockets,Orlando Magic,H. Olajuwon,NaN,H. Olajuwon (725),S. O'Neal (250),A. Hardaway (162),S. O'Neal (3.0)
27,1994,NBA,Houston Rockets,New York Knicks,H. Olajuwon,NaN,H. Olajuwon (664),P. Ewing (293),J. Stockton (157),H. Olajuwon (4.3)
28,1993,NBA,Chicago Bulls,Phoenix Suns,M. Jordan,NaN,M. Jordan (666),C. Barkley (326),K. Johnson (182),C. Barkley (4.6)
29,1992,NBA,Chicago Bulls,Portland Trail Blazers,M. Jordan,NaN,M. Jordan (759),H. Grant (194),J. Stockton (217),M. Jordan (4.1)
30,1991,NBA,Chicago Bulls,Los Angeles Lakers,M. Jordan,NaN,M. Jordan (529),D. Rodman (177),M. Johnson (240),M. Jordan (4.8)

In [41]:
# Process champions df
champions_df['teamname'] = champions_df['Champion']
champions_df = champions_df.drop(['Champion','Lg', 'Runner-Up', 'Finals MVP', 'Unnamed: 5', 'Points', 'Rebounds', 'Assists', 'Win Shares'], axis=1)
champions_df

C:\Users\fateh.luqman\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

    Year               teamname
0   2021        Milwaukee Bucks
1   2020     Los Angeles Lakers
2   2019        Toronto Raptors
3   2018  Golden State Warriors
4   2017  Golden State Warriors
5   2016    Cleveland Cavaliers
6   2015  Golden State Warriors
7   2014      San Antonio Spurs
8   2013             Miami Heat
9   2012             Miami Heat
10  2011       Dallas Mavericks
11  2010     Los Angeles Lakers
12  2009     Los Angeles Lakers
13  2008         Boston Celtics
14  2007      San Antonio Spurs
15  2006             Miami Heat
16  2005      San Antonio Spurs
17  2004        Detroit Pistons
18  2003      San Antonio Spurs
19  2002     Los Angeles Lakers
20  2001     Los Angeles Lakers
21  2000     Los Angeles Lakers
22  1999      San Antonio Spurs
23  1998          Chicago Bulls
24  1997          Chicago Bulls
25  1996          Chicago Bulls
26  1995        Houston Rockets
27  1994        Houston Rockets
28  1993          Chicago Bulls
29  1992          Chicago Bulls
30  1991          Chicago Bulls

In [42]:
# Load the team_name.csv dataset.
csv_path = Path("team_name.csv")
team_name_df = pd.read_csv(csv_path)
team_name_df

                  teamname  abbr
0            Atlanta Hawks   ATL
1           Boston Celtics   BOS
2            Brooklyn Nets   BRK
3            Chicago Bulls   CHI
4        Charlotte Hornets   CHO
5      Cleveland Cavaliers   CLE
6         Dallas Mavericks   DAL
7           Denver Nuggets   DEN
8          Detroit Pistons   DET
9    Golden State Warriors   GSW
10         Houston Rockets   HOU
11          Indiana Pacers   IND
12    Los Angeles Clippers   LAC
13      Los Angeles Lakers   LAL
14       Memphis Grizzlies   MEM
15              Miami Heat   MIA
16         Milwaukee Bucks   MIL
17  Minnesota Timberwolves   MIN
18    New Orleans Pelicans   NOP
19         New York Knicks   NYK
20   Oklahoma City Thunder   OKC
21           Orlando Magic   ORL
22      Philadelphia 76ers   PHI
23            Phoenix Suns   PHO
24  Portland Trail Blazers   POR
25        Sacramento Kings   SAC
26       San Antonio Spurs   SAS
27         Toronto Raptors   TOR
28               Utah Jazz   UTA
29      Washington Wizards   WAS

In [43]:
# Merge Champion teamname with city abbr
champions_df = pd.merge(champions_df, team_name_df, how="inner", on=['teamname'])
champions_df

    Year               teamname abbr
0   2021        Milwaukee Bucks  MIL
1   2020     Los Angeles Lakers  LAL
2   2010     Los Angeles Lakers  LAL
3   2009     Los Angeles Lakers  LAL
4   2002     Los Angeles Lakers  LAL
5   2001     Los Angeles Lakers  LAL
6   2000     Los Angeles Lakers  LAL
7   2019        Toronto Raptors  TOR
8   2018  Golden State Warriors  GSW
9   2017  Golden State Warriors  GSW
10  2015  Golden State Warriors  GSW
11  2016    Cleveland Cavaliers  CLE
12  2014      San Antonio Spurs  SAS
13  2007      San Antonio Spurs  SAS
14  2005      San Antonio Spurs  SAS
15  2003      San Antonio Spurs  SAS
16  1999      San Antonio Spurs  SAS
17  2013             Miami Heat  MIA
18  2012             Miami Heat  MIA
19  2006             Miami Heat  MIA
20  2011       Dallas Mavericks  DAL
21  2008         Boston Celtics  BOS
22  2004        Detroit Pistons  DET
23  1998          Chicago Bulls  CHI
24  1997          Chicago Bulls  CHI
25  1996          Chicago Bulls  CHI
26  1993          Chicago Bulls  CHI
27  1992          Chicago Bulls  CHI
28  1991          Chicago Bulls  CHI
29  1995        Houston Rockets  HOU
30  1994        Houston Rockets  HOU

In [45]:
champions_df['Year'] = champions_df['Year'].astype(str).str.slice(start=2)
#champions_df = champions_df.drop(['teamname'], axis = 1)
champions_df

   Year               teamname abbr
0    21        Milwaukee Bucks  MIL
1    20     Los Angeles Lakers  LAL
2    10     Los Angeles Lakers  LAL
3    09     Los Angeles Lakers  LAL
4    02     Los Angeles Lakers  LAL
5    01     Los Angeles Lakers  LAL
6    00     Los Angeles Lakers  LAL
7    19        Toronto Raptors  TOR
8    18  Golden State Warriors  GSW
9    17  Golden State Warriors  GSW
10   15  Golden State Warriors  GSW
11   16    Cleveland Cavaliers  CLE
12   14      San Antonio Spurs  SAS
13   07      San Antonio Spurs  SAS
14   05      San Antonio Spurs  SAS
15   03      San Antonio Spurs  SAS
16   99      San Antonio Spurs  SAS
17   13             Miami Heat  MIA
18   12             Miami Heat  MIA
19   06             Miami Heat  MIA
20   11       Dallas Mavericks  DAL
21   08         Boston Celtics  BOS
22   04        Detroit Pistons  DET
23   98          Chicago Bulls  CHI
24   97          Chicago Bulls  CHI
25   96          Chicago Bulls  CHI
26   93          Chicago Bulls  CHI
27   92          Chicago Bulls  CHI
28   91          Chicago Bulls  CHI
29   95        Houston Rockets  HOU
30   94        Houston Rockets  HOU

In [46]:
# merge Champions with thier stats from championship year- (PERFROM ML ON THIS DATA SET)
champ_stats_df = pd.merge(champions_df, stats_df, on=['Year', 'abbr'])
champ_stats_df

,Year,teamname,abbr,G,W,L,W/L%,MOV,SOS,SRS,...,eFG%,TS%,TOV%,ORB%,FT/FGA,opp_eFG%,opp_TS%,opp_TOV%,opp_ORB%,opp_FT/FGA
0,21,Milwaukee Bucks,MIL,72,46,26,0.639,5.89,-0.32,5.57,...,0.566,0.593,12.0,23.3,0.177,0.536,0.565,11.5,20.3,0.157
1,20,Los Angeles Lakers,LAL,71,52,19,0.732,5.79,0.49,6.28,...,0.542,0.573,13.3,24.5,0.201,0.515,0.554,14.1,21.2,0.205
2,10,Los Angeles Lakers,LAL,82,57,25,0.695,4.72,0.06,4.78,...,0.496,0.538,12.4,27.6,0.221,0.484,0.522,13.2,25.6,0.195
3,09,Los Angeles Lakers,LAL,82,65,17,0.793,7.66,-0.55,7.11,...,0.513,0.555,12.3,29.4,0.230,0.490,0.530,14.2,27.0,0.213
4,02,Los Angeles Lakers,LAL,82,58,24,0.707,7.12,0.03,7.15,...,0.498,0.534,11.8,28.8,0.218,0.453,0.502,13.0,28.0,0.233
5,01,Los Angeles Lakers,LAL,82,56,26,0.683,3.38,0.37,3.74,...,0.498,0.535,13.3,31.1,0.238,0.468,0.515,12.2,27.5,0.234
6,00,Los Angeles Lakers,LAL,82,67,15,0.817,8.55,-0.14,8.41,...,0.484,0.525,12.7,30.6,0.241,0.443,0.490,13.4,26.9,0.222
7,19,Toronto Raptors,TOR,82,58,24,0.707,6.09,-0.60,5.49,...,0.543,0.579,12.4,21.9,0.198,0.509,0.545,13.1,22.9,0.190
8,18,Golden State Warriors,GSW,82,58,24,0.707,5.98,-0.19,5.79,...,0.569,0.603,14.1,21.0,0.195,0.504,0.539,12.6,23.7,0.186
9,17,Golden State Warriors,GSW,82,67,15,0.817,11.63,-0.28,11.35,...,0.563,0.597,13.2,22.8,0.204,0.486,0.525,13.5,25.1,0.198
10,15,Golden State Warriors,GSW,82,67,15,0.817,10.10,-0.09,10.01,...,0.540,0.571,13.1,24.1,0.184,0.470,0.514,14.3,25.5,0.217
11,16,Cleveland Cavaliers,CLE,82,57,25,0.695,6.00,-0.55,5.45,...,0.524,0.558,12.7,25.1,0.194,0.496,0.534,12.6,21.5,0.205
12,14,San Antonio Spurs,SAS,82,62,20,0.756,7.72,0.28,8.00,...,0.537,0.571,13.5,22.7,0.188,0.482,0.519,12.8,23.6,0.184
13,07,San Antonio Spurs,SAS,82,58,24,0.707,8.43,-0.08,8.35,...,0.521,0.561,13.6,24.2,0.235,0.471,0.511,14.0,24.3,0.201
14,05,San Antonio Spurs,SAS,82,59,23,0.720,7.80,0.03,7.84,...,0.492,0.534,13.2,29.1,0.238,0.452,0.502,14.7,26.4,0.236
15,03,San Antonio Spurs,SAS,82,60,22,0.732,5.41,0.23,5.65,...,0.497,0.541,15.1,28.8,0.253,0.453,0.496,14.2,28.7,0.199
16,99,San Antonio Spurs,SAS,50,37,13,0.740,8.06,-0.94,7.12,...,0.479,0.523,14.6,30.4,0.259,0.423,0.464,13.8,30.5,0.198
17,13,Miami Heat,MIA,82,66,16,0.805,7.87,-0.84,7.03,...,0.552,0.588,13.7,22.2,0.224,0.487,0.527,14.8,27.0,0.200
18,12,Miami Heat,MIA,66,46,20,0.697,5.98,-0.27,5.72,...,0.505,0.549,14.5,26.6,0.238,0.479,0.517,15.8,26.1,0.200
19,06,Miami Heat,MIA,82,52,30,0.634,3.87,-0.27,3.59,...,0.517,0.556,13.9,26.7,0.254,0.477,0.524,12.4,23.6,0.251
20,11,Dallas Mavericks,DAL,82,57,25,0.695,4.23,0.18,4.41,...,0.525,0.565,13.6,24.1,0.222,0.488,0.528,13.0,25.2,0.206
21,08,Boston Celtics,BOS,82,66,16,0.805,10.26,-0.95,9.30,...,0.522,0.569,14.7,26.6,0.267,0.457,0.508,15.2,25.6,0.253
22,04,Detroit Pistons,DET,82,54,28,0.659,5.84,-0.81,5.04,...,0.461,0.511,14.7,30.1,0.247,0.441,0.484,15.5,28.2,0.202
23,98,Chicago Bulls,CHI,82,62,20,0.756,7.11,0.13,7.24,...,0.473,0.516,13.3,35.7,0.219,0.457,0.500,14.7,29.4,0.220
24,97,Chicago Bulls,CHI,82,69,13,0.841,10.80,-0.11,10.70,...,0.511,0.547,12.5,35.9,0.199,0.471,0.509,14.8,30.7,0.196
25,96,Chicago Bulls,CHI,82,72,10,0.878,12.24,-0.44,11.80,...,0.517,0.555,13.1,36.9,0.217,0.482,0.522,16.1,28.9,0.222
26,93,Chicago Bulls,CHI,82,57,25,0.695,6.29,-0.10,6.19,...,0.499,0.535,12.0,36.3,0.199,0.493,0.539,15.4,31.3,0.239
27,92,Chicago Bulls,CHI,82,67,15,0.817,10.44,-0.37,10.07,...,0.518,0.556,11.8,35.1,0.221,0.476,0.520,14.1,30.7,0.219
28,91,Chicago Bulls,CHI,82,61,21,0.744,9.10,-0.53,8.57,...,0.521,0.560,12.8,34.7,0.225,0.488,0.533,15.3,31.2,0.226
29,95,Houston Rockets,HOU,82,47,35,0.573,2.12,0.20,2.32,...,0.529,0.568,15.0,26.9,0.232,0.489,0.527,13.9,32.3,0.199
30,94,Houston Rockets,HOU,82,58,24,0.707,4.32,-0.12,4.19,...,0.507,0.545,15.0,27.6,0.218,0.458,0.497,13.3,30.3,0.192

In [48]:
# Load the cy_stats.csv dataset.
csv_path = Path("cy_stats.csv")
cy_stats_df = pd.read_csv(csv_path)
cy_stats_df

,Rk,Season,Tm,Lg,G,W,L,W/L%,MOV,SOS,...,eFG%,TS%,TOV%,ORB%,FT/FGA,opp_eFG%,opp_TS%,opp_TOV%,opp_ORB%,opp_FT/FGA
0,1,2021-22,MIA,NBA,6,5,1,0.833,17.00,1.07,...,0.525,0.565,13.6,27.5,0.197,0.464,0.501,13.4,15.9,0.181
1,2,2021-22,WAS,NBA,7,5,2,0.714,2.57,1.11,...,0.505,0.549,11.5,20.4,0.213,0.492,0.535,11.0,20.5,0.197
2,3,2021-22,UTA,NBA,6,5,1,0.833,12.83,-3.08,...,0.526,0.574,14.2,24.6,0.236,0.450,0.485,10.8,23.1,0.164
3,4,2021-22,TOR,NBA,8,5,3,0.625,4.63,1.25,...,0.487,0.518,12.1,29.8,0.158,0.521,0.554,16.8,20.6,0.178
4,5,2021-22,SAS,NBA,7,2,5,0.286,-0.43,-1.50,...,0.526,0.542,12.2,22.2,0.113,0.549,0.568,15.2,21.4,0.130
5,6,2021-22,SAC,NBA,6,3,3,0.500,-2.83,-1.06,...,0.508,0.543,12.1,21.7,0.177,0.504,0.540,10.1,24.7,0.187
6,7,2021-22,POR,NBA,7,3,4,0.429,1.86,-0.95,...,0.540,0.565,13.4,25.9,0.154,0.540,0.560,12.2,19.1,0.146
7,8,2021-22,PHO,NBA,5,2,3,0.400,-5.00,-1.64,...,0.511,0.539,12.5,20.4,0.175,0.552,0.571,13.4,18.7,0.122
8,9,2021-22,PHI,NBA,7,5,2,0.714,8.57,-2.13,...,0.571,0.607,12.7,19.0,0.186,0.507,0.537,13.0,26.3,0.160
9,10,2021-22,ORL,NBA,8,2,6,0.250,-7.63,3.26,...,0.518,0.551,15.3,24.4,0.183,0.525,0.554,10.8,25.5,0.174
10,11,2021-22,OKC,NBA,7,1,6,0.143,-13.14,0.10,...,0.472,0.505,13.8,18.3,0.164,0.541,0.565,12.9,22.8,0.133
11,12,2021-22,NYK,NBA,7,5,2,0.714,4.86,0.52,...,0.558,0.585,12.6,20.6,0.180,0.501,0.543,11.6,23.2,0.195
12,13,2021-22,NOP,NBA,7,1,6,0.143,-6.71,1.23,...,0.491,0.525,14.0,26.4,0.160,0.532,0.569,12.2,21.6,0.196
13,14,2021-22,MIN,NBA,6,3,3,0.500,0.17,-4.22,...,0.486,0.516,14.3,26.4,0.153,0.486,0.525,16.6,30.5,0.197
14,15,2021-22,MIL,NBA,7,3,4,0.429,-3.57,3.87,...,0.509,0.541,12.5,20.1,0.171,0.535,0.564,12.2,20.1,0.173
15,16,2021-22,ATL,NBA,7,4,3,0.571,1.29,-0.98,...,0.507,0.540,11.6,27.9,0.157,0.502,0.540,10.6,20.8,0.166
16,17,2021-22,MEM,NBA,7,4,3,0.571,-2.86,1.75,...,0.512,0.542,13.0,28.6,0.142,0.558,0.583,13.0,21.5,0.161
17,18,2021-22,LAL,NBA,7,4,3,0.571,0.57,-4.88,...,0.542,0.564,14.3,20.8,0.143,0.518,0.549,14.4,26.2,0.197
18,19,2021-22,LAC,NBA,6,2,4,0.333,-0.83,-2.11,...,0.486,0.511,10.7,18.1,0.135,0.496,0.531,16.3,25.8,0.180
19,20,2021-22,IND,NBA,8,2,6,0.250,-2.00,5.05,...,0.538,0.568,14.9,22.3,0.163,0.525,0.558,12.7,22.4,0.184
20,21,2021-22,HOU,NBA,6,1,5,0.167,-7.67,-3.49,...,0.496,0.529,16.8,21.9,0.190,0.517,0.548,14.1,21.8,0.184
21,22,2021-22,GSW,NBA,6,5,1,0.833,7.83,-6.39,...,0.538,0.565,14.4,20.3,0.160,0.499,0.524,13.5,15.8,0.140
22,23,2021-22,DET,NBA,6,1,5,0.167,-11.00,3.91,...,0.464,0.499,14.6,22.6,0.176,0.559,0.592,16.2,18.7,0.182
23,24,2021-22,DEN,NBA,7,4,3,0.571,2.57,-1.72,...,0.536,0.551,16.3,18.5,0.109,0.493,0.524,15.0,21.4,0.156
24,25,2021-22,DAL,NBA,6,4,2,0.667,-4.67,-1.66,...,0.477,0.504,11.6,20.1,0.152,0.509,0.534,13.5,22.2,0.143
25,26,2021-22,CLE,NBA,8,4,4,0.500,-1.13,-0.62,...,0.499,0.536,14.1,25.4,0.195,0.513,0.534,14.1,27.2,0.120
26,27,2021-22,CHO,NBA,8,5,3,0.625,2.50,1.92,...,0.537,0.563,11.3,26.0,0.165,0.540,0.576,14.0,25.9,0.184
27,28,2021-22,CHI,NBA,7,6,1,0.857,8.71,-0.23,...,0.530,0.575,12.0,17.3,0.218,0.492,0.524,15.1,25.1,0.155
28,29,2021-22,BRK,NBA,7,4,3,0.571,0.00,4.13,...,0.530,0.562,14.0,15.9,0.189,0.479,0.512,10.7,21.0,0.162
29,30,2021-22,BOS,NBA,7,2,5,0.286,-5.86,2.91,...,0.501,0.538,12.0,20.3,0.181,0.528,0.568,13.2,24.2,0.219