In [11]:
# Random Forest Model
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
stats_df = pd.read_csv('stats_target_clean.csv')
stats_df.head()

,Position,Season,Tm,Team_Name,Lg,G,W,L,W/L%,MOV,...,eFG%,TS%,TOV%,ORB%,FT/FGA,opp_eFG%,opp_TS%,opp_TOV%,opp_ORB%,opp_FT/FGA
0,0,2020-21,WAS,Washington Wizards,NBA,72,34,38,0.472,-1.83,...,0.531,0.569,12.3,21.3,0.221,0.539,0.576,12.5,22.4,0.217
1,0,2020-21,UTA,Utah Jazz,NBA,72,52,20,0.722,9.25,...,0.563,0.597,12.7,24.5,0.195,0.507,0.537,10.3,20.7,0.159
2,0,2020-21,TOR,Toronto Raptors,NBA,72,27,45,0.375,-0.47,...,0.529,0.567,11.9,20.8,0.196,0.543,0.584,14.4,23.7,0.234
3,0,2020-21,SAS,San Antonio Spurs,NBA,72,33,39,0.458,-1.74,...,0.517,0.554,10.2,20.0,0.192,0.541,0.570,11.8,22.7,0.174
4,0,2020-21,SAC,Sacramento Kings,NBA,72,31,41,0.431,-3.68,...,0.549,0.578,12.0,21.3,0.185,0.557,0.591,12.1,25.0,0.199

In [12]:
stats_df.drop('Lg', axis=1, inplace=True)

In [14]:
stats_df.head()

,Position,Season,Tm,Team_Name,G,W,L,W/L%,MOV,SOS,...,eFG%,TS%,TOV%,ORB%,FT/FGA,opp_eFG%,opp_TS%,opp_TOV%,opp_ORB%,opp_FT/FGA
0,0,2020-21,WAS,Washington Wizards,72,34,38,0.472,-1.83,-0.01,...,0.531,0.569,12.3,21.3,0.221,0.539,0.576,12.5,22.4,0.217
1,0,2020-21,UTA,Utah Jazz,72,52,20,0.722,9.25,-0.29,...,0.563,0.597,12.7,24.5,0.195,0.507,0.537,10.3,20.7,0.159
2,0,2020-21,TOR,Toronto Raptors,72,27,45,0.375,-0.47,-0.07,...,0.529,0.567,11.9,20.8,0.196,0.543,0.584,14.4,23.7,0.234
3,0,2020-21,SAS,San Antonio Spurs,72,33,39,0.458,-1.74,0.15,...,0.517,0.554,10.2,20.0,0.192,0.541,0.570,11.8,22.7,0.174
4,0,2020-21,SAC,Sacramento Kings,72,31,41,0.431,-3.68,0.23,...,0.549,0.578,12.0,21.3,0.185,0.557,0.591,12.1,25.0,0.199

In [15]:
# Generate our categorical variable list
stats_cat = stats_df.dtypes[stats_df.dtypes == "object"].index.tolist()

# Check the number of unique values in each column
stats_df[stats_cat].nunique()

Season       32
Tm           38
Team_Name    34
dtype: int64

In [17]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(stats_df[stats_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(stats_cat)
encode_df.head()

,Season_1989-90,Season_1990-91,Season_1991-92,Season_1992-93,Season_1993-94,Season_1994-95,Season_1995-96,Season_1996-97,Season_1997-98,Season_1998-99,...,Team_Name_Philadelphia 76ers,Team_Name_Phoenix Suns,Team_Name_Portland Trail Blazers,Team_Name_Sacramento Kings,Team_Name_San Antonio Spurs,Team_Name_Seattle Supersonics,Team_Name_Toronto Raptors,Team_Name_Utah Jazz,Team_Name_Vancouver Grizzlies,Team_Name_Washington Wizards
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
# Merge one-hot encoded features and drop the originals
stats_df = stats_df.merge(encode_df,left_index=True, right_index=True)
stats_df = stats_df.drop(stats_cat,1)
stats_df.head(20)

,Position,G,W,L,W/L%,MOV,SOS,SRS,Pace,ORtg,...,Team_Name_Philadelphia 76ers,Team_Name_Phoenix Suns,Team_Name_Portland Trail Blazers,Team_Name_Sacramento Kings,Team_Name_San Antonio Spurs,Team_Name_Seattle Supersonics,Team_Name_Toronto Raptors,Team_Name_Utah Jazz,Team_Name_Vancouver Grizzlies,Team_Name_Washington Wizards
0,0,72,34,38,0.472,-1.83,-0.01,-1.85,104.1,111.2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0,72,52,20,0.722,9.25,-0.29,8.97,98.5,117.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0,72,27,45,0.375,-0.47,-0.07,-0.54,99.2,112.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0,72,33,39,0.458,-1.74,0.15,-1.58,98.9,111.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0,72,31,41,0.431,-3.68,0.23,-3.45,100.0,113.6,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0,72,42,30,0.583,1.79,0.01,1.81,98.4,117.8,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2,72,51,21,0.708,5.82,-0.15,5.67,97.2,117.2,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0,72,49,23,0.681,5.58,-0.31,5.28,99.5,113.2,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0,72,21,51,0.292,-9.31,0.29,-9.02,98.7,105.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0,72,22,50,0.306,-10.64,0.51,-10.13,101.0,103.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0,72,41,31,0.569,2.31,-0.18,2.13,95.9,110.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0,72,31,41,0.431,-0.29,0.10,-0.20,100.1,113.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0,72,23,49,0.319,-5.56,0.31,-5.25,101.6,109.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,1,72,46,26,0.639,5.89,-0.32,5.57,102.2,117.2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0,72,40,32,0.556,0.03,-0.09,-0.06,96.6,111.2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0,72,38,34,0.528,1.03,0.04,1.07,100.4,112.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0,72,42,30,0.583,2.79,-0.03,2.77,98.7,109.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0,72,47,25,0.653,6.18,-0.16,6.02,96.9,117.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0,72,34,38,0.472,-0.04,-0.08,-0.13,101.6,112.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0,72,17,55,0.236,-7.90,0.40,-7.50,101.4,107.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
# Remove Position target from features data
y = stats_df.Position
X = stats_df.drop(columns=["Position"])

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [20]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Evaluate the model
y_pred = rf_model.predict(X_test_scaled)
print(f" Random forest predictive accuracy: {accuracy_score(y_test,y_pred):.3f}")

 Random forest predictive accuracy: 0.932

In [21]:
# Define the model - deep neural net
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  24
hidden_nodes_layer2 = 12

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/50
22/22 [==============================] - 2s 7ms/step - loss: 0.5576 - accuracy: 0.7196
Epoch 2/50
22/22 [==============================] - 0s 807us/step - loss: 0.3821 - accuracy: 0.8941
Epoch 3/50
22/22 [==============================] - 0s 807us/step - loss: 0.2851 - accuracy: 0.9199
Epoch 4/50
22/22 [==============================] - 0s 855us/step - loss: 0.2281 - accuracy: 0.9242
Epoch 5/50
22/22 [==============================] - 0s 855us/step - loss: 0.1906 - accuracy: 0.9371
Epoch 6/50
22/22 [==============================] - 0s 855us/step - loss: 0.1609 - accuracy: 0.9371
Epoch 7/50
22/22 [==============================] - 0s 855us/step - loss: 0.1354 - accuracy: 0.9428
Epoch 8/50
22/22 [==============================] - 0s 855us/step - loss: 0.1109 - accuracy: 0.9428
Epoch 9/50
22/22 [==============================] - 0s 902us/step - loss: 0.0885 - accuracy: 0.9456
Epoch 10/50
22/22 [==============================] - 0s 855us/step - loss: 0.0685 - accuracy: 0.9471
Epoch 11/50
22/22 [==============================] - 0s 855us/step - loss: 0.0502 - accuracy: 0.9485
Epoch 12/50
22/22 [==============================] - 0s 855us/step - loss: 0.0345 - accuracy: 0.9471
Epoch 13/50
22/22 [==============================] - ETA: 0s - loss: 0.0668 - accuracy: 1.00 - 0s 855us/step - loss: 0.0194 - accuracy: 0.9485
Epoch 14/50
22/22 [==============================] - 0s 902us/step - loss: 0.0039 - accuracy: 0.9471
Epoch 15/50
22/22 [==============================] - 0s 902us/step - loss: -0.0116 - accuracy: 0.9499
Epoch 16/50
22/22 [==============================] - 0s 855us/step - loss: -0.0264 - accuracy: 0.9499
Epoch 17/50
22/22 [==============================] - 0s 807us/step - loss: -0.0424 - accuracy: 0.9514
Epoch 18/50
22/22 [==============================] - 0s 903us/step - loss: -0.0568 - accuracy: 0.9514
Epoch 19/50
22/22 [==============================] - 0s 902us/step - loss: -0.0732 - accuracy: 0.9514
Epoch 20/50
22/22 [==============================] - 0s 855us/step - loss: -0.0947 - accuracy: 0.9557
Epoch 21/50
22/22 [==============================] - 0s 807us/step - loss: -0.1140 - accuracy: 0.9542
Epoch 22/50
22/22 [==============================] - 0s 902us/step - loss: -0.1300 - accuracy: 0.9485
Epoch 23/50
22/22 [==============================] - 0s 902us/step - loss: -0.1535 - accuracy: 0.9571
Epoch 24/50
22/22 [==============================] - 0s 855us/step - loss: -0.1823 - accuracy: 0.9528
Epoch 25/50
22/22 [==============================] - 0s 760us/step - loss: -0.2108 - accuracy: 0.9571
Epoch 26/50
22/22 [==============================] - 0s 952us/step - loss: -0.2385 - accuracy: 0.9571
Epoch 27/50
22/22 [==============================] - 0s 855us/step - loss: -0.2729 - accuracy: 0.9585
Epoch 28/50
22/22 [==============================] - 0s 855us/step - loss: -0.3083 - accuracy: 0.9557
Epoch 29/50
22/22 [==============================] - 0s 854us/step - loss: -0.3477 - accuracy: 0.9528
Epoch 30/50
22/22 [==============================] - ETA: 0s - loss: -0.8482 - accuracy: 0.937 - 0s 902us/step - loss: -0.3904 - accuracy: 0.9585
Epoch 31/50
22/22 [==============================] - 0s 902us/step - loss: -0.4380 - accuracy: 0.9542
Epoch 32/50
22/22 [==============================] - 0s 902us/step - loss: -0.4900 - accuracy: 0.9599
Epoch 33/50
22/22 [==============================] - 0s 806us/step - loss: -0.5489 - accuracy: 0.9557
Epoch 34/50
22/22 [==============================] - 0s 950us/step - loss: -0.6128 - accuracy: 0.9542
Epoch 35/50
22/22 [==============================] - 0s 855us/step - loss: -0.6790 - accuracy: 0.9499
Epoch 36/50
22/22 [==============================] - 0s 855us/step - loss: -0.7730 - accuracy: 0.9528
Epoch 37/50
22/22 [==============================] - 0s 807us/step - loss: -0.8604 - accuracy: 0.9514
Epoch 38/50
22/22 [==============================] - 0s 1ms/step - loss: -0.9461 - accuracy: 0.9499
Epoch 39/50
22/22 [==============================] - 0s 997us/step - loss: -1.0650 - accuracy: 0.9514
Epoch 40/50
22/22 [==============================] - 0s 853us/step - loss: -1.1929 - accuracy: 0.9499
Epoch 41/50
22/22 [==============================] - 0s 902us/step - loss: -1.2933 - accuracy: 0.9456
Epoch 42/50
22/22 [==============================] - 0s 855us/step - loss: -1.4433 - accuracy: 0.9485
Epoch 43/50
22/22 [==============================] - 0s 853us/step - loss: -1.5831 - accuracy: 0.9456
Epoch 44/50
22/22 [==============================] - 0s 712us/step - loss: -1.7661 - accuracy: 0.9528
Epoch 45/50
22/22 [==============================] - 0s 808us/step - loss: -1.9437 - accuracy: 0.9499
Epoch 46/50
22/22 [==============================] - 0s 855us/step - loss: -2.1191 - accuracy: 0.9413
Epoch 47/50
22/22 [==============================] - 0s 901us/step - loss: -2.3362 - accuracy: 0.9528
Epoch 48/50
22/22 [==============================] - 0s 853us/step - loss: -2.5274 - accuracy: 0.9456
Epoch 49/50
22/22 [==============================] - 0s 807us/step - loss: -2.7185 - accuracy: 0.9471
Epoch 50/50
22/22 [==============================] - 0s 855us/step - loss: -3.0010 - accuracy: 0.9471
8/8 - 0s - loss: 6.3283 - accuracy: 0.8376
Loss: 6.328302383422852, Accuracy: 0.8376068472862244